headersOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/zrianrashid/luca-amsterdam-new"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=86400, stale-while-revalidate=31536000"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=86400, stale-while-revalidate=31536000"

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/reserve.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]